# Generated by Django 5.1 on 2024-09-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('weather_condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['city', 'timestamp'], name='weather_wea_city_29b075_idx'),
        ),
    ]
